### ISSUE TITLE
Change the appearance of the social links on the Press Kit page

### ISSUE THREAD

**Issue by erikalogie** [regen-network/regen-web#1098]
https://www.figma.com/file/ZfOXl4bHBqT2sqmgLBfsA1/Press-Kit?node-id=60%3A0

**Comment by mhagel** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Regen-Registry-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/1098?planning-poker) with ZenHub @flagrede @haveanicedavid

**Comment by haveanicedavid** [comment]
@erikalogie https://deploy-preview-1211--regen-website.netlify.app/press-kit/

**Comment by erikalogie** [comment]
@haveanicedavid part of this task was also to remove the words under the icons, make them smaller, and decrease the height of the background container so that it matches the comps

**Comment by haveanicedavid** [comment]
@erikalogie updated. It would be helpful to have changes itemized in stories like this in the ticket, if it’s not a big hassel on your end

**Comment by erikalogie** [comment]
Sure, sorry about that, will do next time!

Desktop looks good, some small feedback on mobile (it is off-center for some reason and the size of the header is too small, it should be the same size as "Regen Network logos", "Awards", etc.): 
https://monosnap.com/file/uItPFpIl2BHcWacgVdUPjHILIzXGzy

Here is the mobile comp link: https://www.figma.com/file/ZfOXl4bHBqT2sqmgLBfsA1/Press-Kit?node-id=60%3A1801

**Comment by haveanicedavid** [comment]
Thanks @erikalogie ! Your eyes for detail are a lot better than mine :D 

Updated, but the change is currently just on the press-kit page. Other pages the component is used:
- community
- developers
- token
- validators

should show the old design with the updated gradient

**Comment by erikalogie** [comment]
Looks good to go!
