### ISSUE TITLE
Missing Project Start/End Date

### ISSUE THREAD

**Issue by mhagel** [regen-network/regen-web#1366]
**Describe the bug**

Project Pages are missing the project start/end date in the ‘additional info’

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

- Project page (pay attention to the "additonal info" section): https://www.figma.com/file/seUiQM2SPt78KJiDL0Ea8m/Basic-Ecocredits-Ledger-View-%2F-Marketplace?node-id=3495%3A166691

  
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged

**Comment by flagrede** [comment]
@mhagel I might misunderstand this issue but I do see the start/end date on project page
![image.png](https://images.zenhubusercontent.com/62a97d379603eae09036f8bb/1831070a-4967-4d1a-ba59-5285e9f1820a)
![image.png](https://images.zenhubusercontent.com/62a97d379603eae09036f8bb/da9dc1e1-0421-41e5-9570-4d1ccf616331)

**Comment by S4mmyb** [comment]
@flagrede this issue is for the C02 (CFC) Project Pages, not the C01 pages which you are taking pictures of now. This is a fix for @mhagel's PR [#1232](https://github.com/regen-network/regen-web/pull/1232) which missed including the start/end dates.

**Comment by flagrede** [comment]
Oh makes sense, thanks @S4mmyb
