### ISSUE TITLE
Update bridge event status endpoint

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/regen-web#1755]
Bridge status endpoint has been updated to include more information:

- https://hackmd.io/wt8c4YXdTTyi0PAPVMg4cg

The following changes need to be made:

- Update endpoint `${apiUri}/regen/events/${hash}/status` to `${apiUri}/regen/events/${hash}`.
- Update `tx_hash` to `regen_tx_hash` and `destination_tx_hash` to `evm_tx_hash`

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged

**Comment by blushi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Regen-Registry-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/1755?planning-poker) with Zenhub @flagrede @haveanicedavid
