### ISSUE TITLE
Make changes to website main navigation and footer navigation

### ISSUE THREAD

**Issue by erikalogie** [regen-network/regen-web#1786]
Change the main navigation and footer as per the mockup below:
Desktop: https://www.figma.com/file/PzWf8oALasWzgOBl4WhAcC/Homepage%2C-New-Business-Buyers-Page?node-id=568%3A8478&t=zZNVROHkxG3zu4AI-1
Mobile: https://www.figma.com/file/MuSpCtCdU2ns4cFAsPfvsx/Text-Styles-%26-Components-(current)?node-id=3%3A192&t=LV317zVpfEsy35WQ-1

Remove from the website:
- developers, scientists, validators, mainnet, community

Remove instagram and facebook from "join the community" section

Main nav links:
- Corporate buying - https://app.regen.network/buyers/
- Project developers- https://app.regen.network/land-stewards/ (would be great to change the url here to project-developers and do a redirect from /land-stewards
- Registry: https://regennetwork.notion.site/Welcome-to-Regen-Registry-0d55aab2a2d64f27aee2a468df172990
- Explore credits - app.regen.network/projects

Footer links:
- Marketplace: app.regen.network
- Registry: https://regennetwork.notion.site/Welcome-to-Regen-Registry-0d55aab2a2d64f27aee2a468df172990
- Built on Regen: https://regennetwork.notion.site/Built-On-Regen-Network-c6266114116842e389258747454f9f07
- Regen Foundation: https://regen.foundation/ [new tab]
- Cerulean Ventures: https://cerulean.vc/ [new tab]
- Program Guide: https://library.regen.network/v/regen-registry-program-guide/
- Create Methodology: https://library.regen.network/v/regen-registry-program-guide/methodology-development/methodology-development-overview
- Methodology Review: https://library.regen.network/v/regen-registry-program-guide/methodology-development/methodology-review-process
- Methodology Library: https://library.regen.network/v/methodology-library/
- Guides: guides.regen.network
- Governance: https://forum.regen.network/overview
- Docs: https://docs.regen.network/
- Whitepaper: https://regen-network.gitlab.io/whitepaper/WhitePaper.pdf
- $Regen Token: https://www.regen.network/token/
- FAQ: .https://www.regen.network/faq/
- Media: https://www.regen.network/media/
- Press Kit: https://www.regen.network/press-kit/
- Team: /team
- Careers: https://regennetwork.notion.site/Careers-at-Regen-Network-fe7d9645a39843cfb7eaceb7171d95af
- Contact: /contact

**Comment by blushi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Regen-Registry-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/1786?planning-poker) with Zenhub @flagrede @haveanicedavid

**Comment by blushi** [comment]
@erikalogie should we just get rid of the content for developers, scientists, validators, mainnet, community pages on sanity too? maybe it would be safest to export the current content just in case...

**Comment by blushi** [comment]
also on the homepage, "learn more" button is linking to the developers page, what should we do about that? ![image.png](https://images.zenhubusercontent.com/5f801c9560f48dc9cdce4fc8/b8710910-31fb-485d-b566-f38a62b3c619)
should we just remove this page from the nav but keep it?

**Comment by blushi** [comment]
when you said "Remove from the website: ..." in the description above, it rather meant "Remove from the website nav"?

**Comment by blushi** [comment]
regarding the footer links, should all the links that are not website pages open in a new tab?

**Comment by erikalogie** [comment]
@blushi Sarah said that we don't have to remove the pages from the website, but from the navigation for now. Also, we need to add "Resources" somewhere in the footer, I'm waiting for Sarah to give me feedback on where to put it, perhaps under "Company".

**Comment by erikalogie** [comment]
> also on the homepage, "learn more" button is linking to the developers page, what should we do about that? ![image.png](https://camo.githubusercontent.com/45164313b28ffc0479b7816698fb7e7214e941c7b4342428f90a4a5bd7818b7c/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3566383031633935363066343864633963646365346663382f62383731303931302d333166622d343835642d623536362d663338613632623363363139) should we just remove this page from the nav but keep the page itself?

Let's keep the page itself but re-link this button to the developer docs instead for now.

**Comment by erikalogie** [comment]
@blushi I put Resources under "Company" FYI

**Comment by blushi** [comment]
@erikalogie alright thanks!
