### ISSUE TITLE
Make changes to website homepage

### ISSUE THREAD

**Issue by erikalogie** [regen-network/regen-web#1793]
Figma comps: 
Desktop: https://www.figma.com/file/PzWf8oALasWzgOBl4WhAcC/Homepage%2C-New-Business-Buyers-Page?node-id=502%3A811&t=zJ2YAN9KPwf0bL1m-1
Mobile: https://www.figma.com/file/PzWf8oALasWzgOBl4WhAcC/Homepage%2C-New-Business-Buyers-Page?node-id=774%3A12480&t=6BawyzP2Y7u9cf1b-1

### Changes:
- Swap out top header image and make it such that it can be changed in the CMS
- Move up "Regen Marketplace allows project developers..." section
- Add "Our Ecosystem Partners" section
- Add "Featured Credits" section
- Add "impact" section - graphics and text should be editable in the CMS
- Change "why regen network" icons to new ones (Erika tried to do this in the CMS but it ended up looking like this: https://monosnap.com/file/C1mfCMda1vplPtQIT8lDYNtimXVAu1, ideally we would fix the CMS issue as well
- Change the color of "Regen Marketplace" header in "Regen Marketplace allows project developers..." to gradient green instead of solid green, same with Regen Ledger and Regen Marketplace in "Regen Ledger powers Regen Marketplace" header
- Swap out this image for new one: ![image.png](https://images.zenhubusercontent.com/5f899f6595f139894d681577/f1b39846-739f-43b6-931b-661268293d2b)

**Comment by blushi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Regen-Registry-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/1793?planning-poker) with Zenhub @flagrede @haveanicedavid
