### ISSUE TITLE
Separate git push from yarn bump command

### ISSUE THREAD

**Issue by wgwz** [regen-network/regen-web#1803]
I'd prefer if the actions of git push were separate from yarn bump command.
It was surprising to me that it issued a git push for both the main branch and the newest tag.
If we want a single command it would be better as `yarn bump-and-push`.
The `yarn bump` output was surprising too because it only says "pushing tags":
```
➜  regen-web git:(main) yarn bump
yarn run v1.22.19
$ lerna version --conventional-commits
lerna notice cli v6.4.1
lerna info current version 1.1.0
lerna info Looking for changed packages since v1.0.1-fix
lerna info getChangelogConfig Successfully resolved preset "conventional-changelog-angular"

Changes:
 - web-auth: 1.1.0 => 1.2.0 (private)
 - web-components: 1.1.0 => 1.2.0 (private)
 - web-registry: 1.1.0 => 1.2.0 (private)
 - web-storybook: 1.1.0 => 1.2.0 (private)

? Are you sure you want to create these versions? Yes
lerna info execute Skipping releases
lerna info git Pushing tags...
lerna success version finished
✨  Done in 8.45s.
```
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged

**Comment by ryanchristo** [comment]
Updating to be more explicit with `and-push` sounds good to me.

**Comment by wgwz** [comment]
A no-push options does exist as well:
https://github.com/lerna/lerna/tree/main/libs/commands/version#--no-push

**Comment by blushi** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RND-Dev-Team-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/1803?planning-poker) with Zenhub @flagrede
