### ISSUE TITLE
Credits issued & credits tradable show different rounding calculations

### ISSUE THREAD

**Issue by clevinson** [regen-network/regen-web#1834]
If a credit volume is low with fractional amounts, then we have different rounding strategies on the "credits issued" vs "credits tradable" displays.

We should be consistent with our formatting so as not to confuse users.

See here: https://dev.app.regen.network/credit-batches/C56-002-20140701-20141231-001
or here: https://dev.app.regen.network/credit-batches/C55-002-20170101-20170131-001

![Screenshot 2023-03-23 at 5.31.02 PM.png](https://images.zenhubusercontent.com/5fb6f5c5ad906a11f8792bbd/deb201c3-d3ec-4ed7-9acc-d46beafb569a)

![Screenshot 2023-03-23 at 5.15.07 PM.png](https://images.zenhubusercontent.com/5fb6f5c5ad906a11f8792bbd/4817d596-ad01-4cde-9f41-895e5190b514)

**Comment by blushi** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Regen-Registry-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/1834?planning-poker) with Zenhub @flagrede

**Comment by blushi** [comment]
it seems like the issued number is not formatted the same way as the other numbers on `dev` currently (`formatNumberOptions` missing) and we should set up the minimum fraction digits to 2 (same as max)
