### ISSUE TITLE
Switch out blurry regen marketplace image on website homepage with new one attached

### ISSUE THREAD

**Issue by erikalogie** [regen-network/regen-web#1844]
Would be ideal to have this image in the CMS as well.

![Regen Marketplace.png](https://images.zenhubusercontent.com/5f899f6595f139894d681577/e8a2ea6b-3218-48fc-9b21-c0dba3620897)

**Comment by blushi** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Regen-Registry-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/1844?planning-poker) with Zenhub @flagrede

**Comment by blushi** [comment]
put 2 because of the need for adding this to sanity too, wdyt @flagrede?

**Comment by flagrede** [comment]
@blushi  You're right I missed that, let's go for 2 then.
