### ISSUE TITLE
Additional Info on Toucan Batch Metadata doesn't render properly

### ISSUE THREAD

**Issue by clevinson** [regen-network/regen-web#1847]
**Describe the bug**

`regen:toucanVintageTokenId` is not rendering properly on credit batch pages.

I dug a bit into the code with @S4mmyb and was able to identify the problem.  It looks like we have the `<LinkOrDash>` component, which is only rendering if an `regen:tokenURI` field is present in the JSON-LD.  However, at this point in time we don't expect to actually have that field ever filled out (this is blocked on Toucan implementing tokenURIs for all vintages).

So I think what we should do here is for `<LinkOrDash>` components:
- render `-` if there is no `regen:toucanVintageTokenId`
- render the numerical value of `regen:toucanVintageTokenId` if it is present, and if no `regen:tokenURI` is present
- render a hyperlink from `regen:toucanVintageTokenId` to the URL in `regen:tokenURI` if both fields are present in the JSON-LD

**Screenshots**

<img width="1231" alt="Screenshot 2023-04-04 at 4 27 10 PM" src="https://user-images.githubusercontent.com/832188/229937403-e66c129e-5b91-48ca-a094-47d16a9596a4.png">

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged

**Comment by blushi** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Regen-Registry-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/1847?planning-poker) with Zenhub @flagrede

**Comment by blushi** [comment]
> render - if there is no regen:toucanVintageTokenId

I believe we might want to not display this at all if there's no regen:toucanVintageTokenId, otherwise we'll also get this on credit batches from other credit classes which might look weird

**Comment by blushi** [comment]
@flagrede fine to set this as a 1?
