### ISSUE TITLE
Ecocredit batch displays in portfolio when no credits are held by user

### ISSUE THREAD

**Issue by clevinson** [regen-network/regen-web#1848]
**Describe the bug**

When testing out mainnet NCT transfers and basketing UX with Christian last week I ran into a UI bug where ecocredit projects were displayed on my portfolio when I did not have any credits.

You can view the portfolio live here (or see screenshot below):

https://app.regen.network/ecocredits/accounts/regen1l0ck43z80q7uzfd70qzsm9lggwvz3gdy774x30/portfolio

(**Side note**: you have to manually click on the "Portfolio" header section in order for the ecocredits to render at all, we should probably track this as a separate bug)

**To Reproduce**
I believe this can be replicated on testnet as well:

1. Start with some ecocredits from a batch that can be put into a basket
2. On portfolio page, select to "Put" all credits of that batch into the basket
3. See that the ecocredits table of all credits in your portfolio still displays a row for the batch with 0 credits in it, and in Amount Tradable, Amount Retired, Amount Escrowed, it displays 3 dashes "`-`" where the amounts would normally be

**Expected behavior**
After transferring all credits from a batch into a basket, the row corresponding to that ecocredit batch should disappear from the Ecocredits table.

**Screenshots**

<img width="1507" alt="Screenshot 2023-04-03 at 10 37 00 AM" src="https://user-images.githubusercontent.com/832188/229943900-ae62fc7e-6687-4aef-81bb-2c65c1a54e26.png">

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged

**Comment by blushi** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Regen-Registry-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/1848?planning-poker) with Zenhub @flagrede

**Comment by flagrede** [comment]
@blushi I'm guessing we might still want to display the line if the user has retired credits but 0 tradable? We might just want to hide the line in the case where he has 0 on all 3 columns, wdyt ?
