### ISSUE TITLE
Fractional balances of NCT does not display correctly

### ISSUE THREAD

**Issue by clevinson** [regen-network/regen-web#1849]
**Describe the bug**
If a user has a fractional balance of NCT (or any basket token), the UI displays a "`-`" instead of a decimal amount on the portfolio page.

See portfolio page here: https://dev.app.regen.network/ecocredits/accounts/regen1l0ck43z80q7uzfd70qzsm9lggwvz3gdy774x30/portfolio

Make sure to click on "Portfolio" to view the actual portfolio of ecocredits and basket tokens.

Note that when querying for basket balance on-chain (on Regen Redwood), you can see that this user has 0.5 NCT:

```
$ regen q bank balances regen1l0ck43z80q7uzfd70qzsm9lggwvz3gdy774x30
balances:
- amount: "500000"
  denom: eco.uC.NCT
- amount: "789455000"
  denom: uregen
pagination:
  next_key: null
  total: "0"
```

**Expected behavior**
A decimal amount of NCT should be displayed as the "amount available".

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged

**Comment by blushi** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Regen-Registry-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/1849?planning-poker) with Zenhub @flagrede
