### ISSUE TITLE
Fix CSRF failures related to apollo client initialization 

### ISSUE THREAD

**Issue by wgwz** [regen-network/regen-web#1861]
**Describe the bug**

When the application first loads, there are 403 "invalid csrf token" errors issued for `/graphql` requests.
This only happens when the `registry-server` has enabled CSRF protection for the `/graphql` endpoint.
This error does not always happen for all of the `/graphql` requests.
It usually only happens for the first few `/graphql` requests.

Even though some subsequent `/graphql` requests succeed,
the failure of these first few requests can result in missing information in the app.
For example, we first found this issue in production when viewing a public profile page.
It resulted in being unable to see the name and profile image for a specific users profile.

**To Reproduce**

1. In your local development environment make sure that the registry-server is running _**without**_ the `GRAPHIQL_ENABLED` environment variable set.
2. Navigate to a public profile page, i.e. `http://localhost:3000/ecocredits/accounts/<address>/portfolio`
3. Open the network requests tab, and view the requests to `/graphql` that failing.
4. In particular, note how the `x-csrf-token` header's value is `undefined`

**Expected behavior**

There is no reason that the `x-csrf-token` header should be `undefined` in any requests.
Our graphql client should never be initializing with that value.

**Screenshots**

![Screen Shot 2023-04-06 at 5 06 58 PM](https://user-images.githubusercontent.com/10120306/230494126-c1b8dcc4-04c6-4668-911f-45c4aad77ff9.jpg)

**Additional context**

The most relevant parts of the code include:
- `web-registry/src/apollo.tsx`
- `web-registry/src/lib/clients/apolloClientFactory.ts`
- `web-registry/src/index.tsx` (where `AuthApolloProvider` is initialized)

Another part of the code that may be helpful since it involves a request that requires a CSRF token:
- `web-registry/src/lib/wallet/hooks/useLogin.tsx`

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged

**Comment by wgwz** [comment]
I was looking at this some more today, and I'm thinking that the culprit of the bug might actually be the fact that [the `getPartyByAddrQuery` react-query function catches, rather than throws errors](https://github.com/regen-network/regen-web/blob/ddb5ad02fa2898aae79a545cd8a23a0ffc1c7650/web-registry/src/lib/queries/react-query/registry-server/graphql/getPartyByAddrQuery/getPartyByAddrQuery.ts#L14-L24). This breaks [the retry rules of the react-query library](https://tanstack.com/query/v4/docs/react/guides/query-retries), AFAICT. To quote the react-query docs:

> When a useQuery query fails (the query function throws an error), TanStack Query will automatically retry the query if that query's request has not reached the max number of consecutive retries (defaults to 3) or a function is provided to determine if a retry is allowed.

I haven't been able to prove this is the case locally. I think maybe a good next step is to see if it can be reproduced in a deploy-preview environment. But I wanted to write about it first, in case either of you thoughts @blushi and @flagrede .

**Comment by flagrede** [comment]
That's correct we usually combine try-catch block with the enabled flag to make sure that we trigger the request at the right time. Given that we have all data to perform a request if a request fail we do not expect it to work while retrying with the same parameters. Could we add some more parameters to the enabled flag to prevent the failed request from putting undefined in the cache?

**Comment by wgwz** [comment]
I believe that a compounding issue here is the following.
It seems that mobile browsers have different settings than desktop browsers in regards to cookies.

In our setup, all deploy previews are considered 3rd party contexts because our cookies domain is `api-staging.registry.regen.network` and the deploy preview domain is obviously not a subdomain of regen.network.
This means our CSRF cookie in a deploy preview is considered a 3rd party cookie.

My profile in the deploy preview:
https://deploy-preview-1874--regen-registry.netlify.app/ecocredits/accounts/regen1rn2mn8p0j3kqgglf7kpn8eshymgy5sm8w4wmj4/portfolio

On my desktop chrome browser, the effect of this can be seen as follows:
1. In a regular chrome window, I can see my profile.
2. In an incognito window, I cannot see my profile.

Why the difference between 1 and 2?
Because chrome desktop incognito mode blocks all third party cookies by default!
The same rule applies for Safari by default:
https://alvarotrigo.com/blog/third-party-cookies-safari/
And Firefox recently is rolling out a similar rule:
https://blog.mozilla.org/en/mozilla/firefox-rolls-out-total-cookie-protection-by-default-to-all-users-worldwide/

So, this issue is compounded difficulty because of third-party cookies, and the plethora of rules various browsers have regarding them.
Whew, OK, at least it's understandable.

So where does that leave us with this issue?

Currently, I'm using google chrome or firefox (which allows third party cookies, at least for me) to compare these two deployments:
1. https://deploy-preview-1874--regen-registry.netlify.app/ecocredits/accounts/regen1rn2mn8p0j3kqgglf7kpn8eshymgy5sm8w4wmj4/portfolio
2. https://dev.app.regen.network/ecocredits/accounts/regen1rn2mn8p0j3kqgglf7kpn8eshymgy5sm8w4wmj4/portfolio

Both of these are connected the `api-staging.registry.regen.network`.
And both of these are successfully respecting the CSRF cookie.
The first link is set as a third-party cookie that chrome respects.
The second link is consider a "first-party" context, so there is no issue at all with respecting the cookie.

With that said, the second link is not working, it doesn't show the profile info correctly.
Whereas the first link does work correctly (because of changes introduced in the PR for this task).

So what I'm proposing is that if we are happy with the fix, and we deploy it to `dev`, I would expect it to work there, in all browsers because it would be a first-party context.
Otherwise, adjusting browsers to accept third-party cookies should make the deploy previews work.
However, Safari seems to have particularly strict rules regarding cookies, which might require more adjustment.

The upshot is that I think if we deploy the fix to `dev` and `main`, and re-enable CSRF on graphql, it should work ok.
