### ISSUE TITLE
Remove team page from website and other small related updates

### ISSUE THREAD

**Issue by erikalogie** [regen-network/regen-web#1908]
Because we have the new corporate site now, we should remove the team page from the Regen Network website as to not have redundant information. 

- Remove team page
- Remove team section from Press Kit page
- Update the footer as in this comp: https://www.figma.com/file/cCuNGeO2gLL7b6AsRsE8n6/Resources?type=design&node-id=1103%3A6889&t=Ratdh4Kg9pSIbKs5-1 (move community calendar, add Regen Network Development PBC link to https://www.regenlabs.earth/, remove team and careers links, change "company" header to "more")

**Comment by blushi** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Regen-Registry-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/1908?planning-poker) with Zenhub @flagrede
