### ISSUE TITLE
Delete ghost pages

### ISSUE THREAD

**Issue by erikalogie** [regen-network/regen-web#1924]
https://www.notion.so/regennetwork/Website-H1-2023-roadmap-758b1e30586147708ff274523db913f2?p=60f4b14a8d544593b0f84729e1de979a&pm=s

redirect to homepage

**Comment by blushi** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Regen-Registry-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/1924?planning-poker) with Zenhub @flagrede
