### ISSUE TITLE
Add label mapping for unknown credit class, project and batch metadata fields

### ISSUE THREAD

**Issue by blushi** [regen-network/regen-web#1941]
**Is your feature request related to a problem? Please describe.**
Currently, every time we add a new field to credit class, project or batch metadata, we need to add support for it on the front-end so it gets displayed on the credit class, project or batch pages respectively.

**Describe the solution you'd like**
As a follow-up of what was proposed in https://www.notion.so/regennetwork/Standardized-Project-Metadata-Review-a10b3a988c224af09efe28606a7cce6e, we should add field name / label mapping support for unknown metadata fields (metadata that can be specific to a credit class and its projects/batches). Those fields are displayed in the "additional info" part of the credit class, project and batch pages so we can just loop through them and display them there. 

Extract from the notion doc linked above with more detailed proposal:

> The following solution only implies changes on the front-end, and no changes in the metadata itself have to be done:
> 
> 1. Exclude the standardized fields from the incoming metadata, meaning we end up with an object that only has non standardized fields, e.g. for Toucan projects:
> 
> ```tsx
> {
> 	'@context': { ... },
> 	'regen:toucanVintageTokenId': 123,
> 	'regen:toucanURI': 'some.uri'
> }
> ```
> 
> 1. Loop through those fields:
>     1. create the label from the field name programmatically: dropping the IRI prefix and then converting camel case to title case
>     2. based on a predefined list of value types (e.g. strings, name with URL, list, etc.), display the field value using the corresponding rendering component

_Please note that we should display those fields there only if they are not already displayed elsewhere. This is the case for instance for `vcsMethodology` or the CFC `regen:offsetProtocol` which relate to the project methodology and are displayed in the credit class card at the top of the project page._

We might also need to adapt how we handle JSON-LD compaction on the front-end. We might want to include the incoming metadata context to account for fields that might not be in our existing `COMPACTED_CONTEXT`

**Additional context (optional)**
New non standardized metadata fields could be handled in the future without any front-end changes and this could be particularly useful for community credits too.

cc/ @clevinson @S4mmyb 

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels and zenhub epics applied
- [x] Appropriate contributors tagged

**Comment by S4mmyb** [comment]
Awesome, thanks @blushi ! I think this looks good, though I'm also wondering if we've explored the `rdfs:label` property as an alternative to converting to camel case. I'm thinking using some sort of label property would offer users advantages in that it allows the user dissociate the variable from the front-end label if they want that flexibility. Also it might allow us to have more flexible code, because you only really need to change the label name in the schema.

**Comment by blushi** [comment]
yeah that's a good idea @S4mmyb
I guess we could first look for any `rdfs:label` and if there's none, then fallback to our default mapping

**Comment by ryanchristo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Regen-Registry-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/1941?planning-poker) with Zenhub @blushi @wgwz

**Comment by blushi** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Regen-Registry-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/1941?planning-poker) with Zenhub @flagrede

**Comment by blushi** [comment]
After further discussions with @clevinson and @S4mmyb about this, we don't want to repeat `rdfs:label`'s in the metadata itself. If we want the label to be more customizable instead, this should be defined in a dedicated RDF schema (whether it's part of the vocabulary itself or not) so the labels are only defined once per fields.
So as part this task, we'll only implement automatic field name / label mapping.
