### ISSUE TITLE
Unable to save updated project description in project edit flow 

### ISSUE THREAD

**Issue by S4mmyb** [regen-network/regen-web#1951]
**Describe the bug**

I am unable to update the project story for the evergreen and east project page in the project edit ui on mainnet. When I try to edit the story and fix the paragraph spacing and hit save, the UI says my changes has been saved but the project page does not update. When I try to leave the edit page, it asks if I want to discard my changes which indicates that it is not saving on-click. 

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://github.com/regen-network/regen-web/assets/67330492/f1743446-3c22-4d91-9bc0-ee3f5395877a)
![image](https://github.com/regen-network/regen-web/assets/67330492/6fe362c9-cedb-4289-9343-6d97901639d7)
![image](https://github.com/regen-network/regen-web/assets/67330492/72d86652-f0b8-41a3-805b-ad76a00818c7)

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged

**Comment by ryanchristo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RND-Dev-Team-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/1951?planning-poker) with Zenhub @blushi @wgwz

**Comment by blushi** [comment]
I can't reproduce it locally so I asked @s4mmyb some more details by DM

**Comment by ryanchristo** [comment]
Confirmed and tested with sam. This is no longer an issue.
