### ISSUE TITLE
Redirect from /team to homepage

### ISSUE THREAD

**Issue by erikalogie** [regen-network/regen-web#1956]
Any of the pages that were removed recently should have redirects as some are still being indexed by google

**Comment by wgwz** [comment]
> Any of the pages that were removed recently should have redirects as some are still being indexed by google

hey @erikalogie do you have a list of the other pages you have in mind here?

i'm seeing this as the original task for removing the team page:
https://github.com/regen-network/regen-web/issues/1908

but it looks like that was the only page that was removed that would need a redirect (based on what i'm seeing there)
