### ISSUE TITLE
Implement remaining queries based on indexer for improved load performance

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/regen-web#1963]
- Txs query on stats page - activity table
- Adding tx hash to batch data (`addDataToBatches`)

**Comment by ryanchristo** [comment]
@blushi can you identify the queries we need to update to complete epic #977? :pray:

**Comment by blushi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RND-Dev-Team-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/1963?planning-poker) with Zenhub @flagrede @ryanchristo @wgwz

**Comment by ryanchristo** [comment]
Work started in #2018 but dependent upon https://github.com/regen-network/indexer/issues/32.
