### ISSUE TITLE
Mobile login does not work in a mobile browser

### ISSUE THREAD

**Issue by clevinson** [regen-network/regen-web#1972]
**Describe the bug**
Sarah B is prepping for some demos she's wanting to do at the conferences she's at in europe this week. For this, attendees will get a business card w/ a QR Code linking to a project page and they will be able to buy some credits & retire them on mobile.

I was testing this out just now and found that login on mobile (when using the app.regen.network domain in a mobile browser) doesn't work.  I can log in fine if i am using the Keplr App's built-in browser to load the regen marketplace, but if i am on mobile safari or mobile chrome, the deep-linking to Keplr to manage the login stalls. I get a spinning dial in the Keplr app, and then eventually i just see hte Keplr app normally.  When i go back to the browser, it looks like i never logged in, and prompts me to connect via WalletConnect again.

**To Reproduce**
1. Go to 'app.regen.network' on mobile browser (tested on iOS Mobile Safari & Mobile Chrome)
2. Click on 'Login' => "Wallet Connect" => Press "Open" in the 'Open in "Keplr"' dialog box
3. Deep linking should work, spinning dial loads on Keplr app
4. Spinning dial disappears on Keplr app, returning to normal Keplr app view
5. Go back to browser, see that user is still not logged in

**Expected behavior**
In Step 5, I expect to see myself logged in to the account associated w/ the Keplr mobile app.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: iPhone 10x
 - OS: 16.0.2
 - Browser: Mobile Safari, Mobile Chrome
 - Version: 

**Additional context**

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged

**Comment by blushi** [comment]
After investigating, this issue is actually related to wallet connect. If you try to connect via wallet connect, even from desktop, it won't work.

We should migrate to wallet connect v2 (existing issue: https://github.com/regen-network/regen-registry/issues/1537) because we use v1 which has been shut down recently: https://medium.com/walletconnect/weve-reset-the-clock-on-the-walletconnect-v1-0-shutdown-now-scheduled-for-june-28-2023-ead2d953b595, hence we can't connect to the relay server bridge.walletconnect.org

**Comment by clevinson** [comment]
A band-aid solution (if this issue ends up being too thorny, challenging to implement in the short term), would be to on login, deep-link users to the same page within the regen app in the Keplr mobile app.  If we can't deep-link to specific page, then just deep-linking them to the Keplr app and communicate that logged in functionality is only currently supported from within Keplr app.

**Comment by blushi** [comment]
Asked the Keplr team whether that's possible to deep link users to a specific page within the regen app in the Keplr mobile app: https://github.com/chainapsis/keplr-wallet/issues/797
In the mean time, that should be possible to deep link just to the Keplr app using 'keplrwallet://' in iOS and `intent:#Intent;package=com.chainapsis.keplr;scheme=keplrwallet;end;` in Android.

**Comment by wgwz** [comment]
@blushi would it be helpful to put up a redirect in the registry-server for that?
the thought being that we could have a single url that redirects users to either of those depending on the OS info in the headers?

**Comment by wgwz** [comment]
https://www.npmjs.com/package/ua-parser-js
