### ISSUE TITLE
Add impact data to C04 credit class

### ISSUE THREAD

**Issue by blushi** [regen-network/regen-web#1973]
We should create an off-chain credit class in the db and add the impact IRIs to the `credit_class_version.metadata`, making sure the related impact IRI are also in Sanity https://regen.sanity.studio/desk/shared;ecologicalImpact 

Primary impact: Soil Organic Carbon (regen:SoilOrganicCarbon)
Co-benefit 1: Biodiversity (regen:Biodiversity)
Co-benefit 2: Water Infiltration (regen:WaterInfiltration)

**Comment by blushi** [comment]
@erikalogie could you provide the impact list for C04?

**Comment by erikalogie** [comment]
@blushi the impact list is now in the description

**Comment by blushi** [comment]
Added: https://app.regen.network/credit-classes/C04
