### ISSUE TITLE
Add image and description to on-chain classes programs

### ISSUE THREAD

**Issue by blushi** [regen-network/regen-web#1989]
**Is your feature request related to a problem? Please describe.**
We want to display some logo and description for the program on project pages.
Currently for all main net credit classes (C01, C02, C03 and C04), we get the program info from the on chain class metadata, which doesn't have those additional info.

**Describe the solution you'd like**
As it's currently implemented, we can also get the program info from the off-chain class `registry_id` field. Updating this seems the easiest rather than coordinating on chain classes updates.
- For C01 and C03, we should use the existing `party` with "Verra" as name (id: '1b26f7d4-dd9a-11eb-97c8-0ab192efaa7b') as their off-chain class `registry_id` and update Verra party description to: "Verra catalyzes measurable climate action and sustainable development outcomes by driving large-scale investment to activities that achieve them."
- For C02, we should create the following `party` and link it to the off-chain C02 class `registry_id`:
  - name: City Forest Credits
  - website_link: https://www.cityforestcredits.org/ 
  - description: "We are a nonprofit carbon registry that issues third-party verified City Forest Carbon+ Credits from tree planting and preservation projects in cities."
  - image: ![City Forest Credits](https://github.com/regen-network/regen-web/assets/8460237/5e94da72-a8ea-4461-8ad8-729ac4f014dc)
  
- For C04, the program is "Regen Registry", a party with this name already exists (id: 'bfbd845e-3bcb-11ec-8874-0ab192efaa7b') and we need to update its description to "Regen Registry is an ecological service registry operating in the voluntary market that aims to support climate action by accelerating the adoption of nature-based solutions." and its website_link to https://registry.regen.network/
____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels and zenhub epics applied
- [x] Appropriate contributors tagged

**Comment by erikalogie** [comment]
Verra description: Verra catalyzes measurable climate action and sustainable development outcomes by driving large-scale investment to activities that achieve them.

City Forest Credits: We are a nonprofit carbon registry that issues third-party verified City Forest Carbon+ Credits from tree planting and preservation projects in cities. 

![City Forest Credits](https://github.com/regen-network/regen-web/assets/8460237/5e94da72-a8ea-4461-8ad8-729ac4f014dc)

**Comment by erikalogie** [comment]
@blushi I just noticed this is also an issue for C04, we have no description or image for Regen Registry and the link to it is broken

**Comment by blushi** [comment]
description updated

**Comment by ryanchristo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RND-Dev-Team-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/1989?planning-poker) with Zenhub @blushi @wgwz

**Comment by ryanchristo** [comment]
Is this related to https://github.com/regen-network/rnd-dev-team/issues/1653? Looks like maybe some overlap.

**Comment by blushi** [comment]
No this isn't related. This issue is only about adding some data to the postgres db while https://github.com/regen-network/rnd-dev-team/issues/1653 needs some code changes.

**Comment by blushi** [comment]
Done, this can be seen on:
https://app.regen.network/credit-classes/C01
https://app.regen.network/credit-classes/C02
https://app.regen.network/credit-classes/C03
https://app.regen.network/credit-classes/C04

**Comment by erikalogie** [comment]
this looks good!
