### ISSUE TITLE
Wrong font for project stakeholders names on project page

### ISSUE THREAD

**Issue by blushi** [regen-network/regen-web#1995]
**Describe the bug**
The font used for the project stakeholders names on project pages is wrong, it uses Muli.

**To Reproduce**
Go to https://app.regen.network/project/C03-002

**Expected behavior**
The font should be Lato, just as on the credit class page: https://app.regen.network/credit-classes/C03

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5f801c9560f48dc9cdce4fc8/74be9221-94b9-46dc-9f6c-944b6f31654f)

____

## For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels and zenhub epics applied
- [x] Appropriate contributors tagged

**Comment by ryanchristo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RND-Dev-Team-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/1995?planning-poker) with Zenhub @blushi @wgwz
