### ISSUE TITLE
Improve loading time of credit classes by issuer

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/regen-web#2000]
**Is your feature request related to a problem? Please describe.**

When loading credit classes that an account is an issuer for during the project creation process, it takes a significant amount of time to load the credit classes from the test network, i.e. where we have a large number of credit classes. This is currently not an issue on the main network because we have so few credit classes but likely to become a problem over time.

**Describe the solution you'd like**

Use credit classes by issuer query from the indexer (https://github.com/regen-network/indexer/issues/30)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged

**Comment by ryanchristo** [comment]
This also applies to the portfolio page when loading the tabs available to the user.

**Comment by blushi** [comment]
> This also applies to the portfolio page when loading the tabs available to the user.

For that, I believe we have this issue: https://github.com/regen-network/rnd-dev-team/issues/1757

**Comment by blushi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RND-Dev-Team-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/2000?planning-poker) with Zenhub @flagrede @ryanchristo @wgwz

**Comment by ryanchristo** [comment]
This should now be unblocked following the most recent changes to the indexer.

**Comment by wgwz** [comment]
See here for query info:
https://github.com/regen-network/indexer/pull/36#issuecomment-1687275538

**Comment by wgwz** [comment]
The staging indexer is connected to redwood and redwood is not archive node.
Therefore staging indexer can only "see" events that have not been pruned from state.
As such, only the credit class id's listed below will be available to the indexer api endpoints.
Please keep this in mind while testing!
```
 class_id 
----------
 C63
 C62
 C60
 C61
 KSH01
```

The production indexer does not have this issue because it is connected to an archive node.
```
 class_id 
----------
 C03
 C04
 C02
```

**Comment by wgwz** [comment]
The full list of issuers for all classes can be found in staging and production by running this query:
```graphql
{
  allClassIssuers(condition: {latest: true}) {
    nodes {
      blockHeight
      classId
      issuer
    }
  }
}
```
Staging: https://api-staging.regen.network/indexer/v1/graphiql
Production: https://api.regen.network/indexer/v1/graphiql
