### ISSUE TITLE
Change link to Registry in website main navigation to registry.regen.network

### ISSUE THREAD

**Issue by erikalogie** [regen-network/regen-web#2021]
We should not link to the notion page anymore

**Comment by ryanchristo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RND-Dev-Team-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/2021?planning-poker) with Zenhub @flagrede @ryanchristo
