### ISSUE TITLE
Fix metadata reference in project creation/edit flow

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/regen-web#2036]
**Describe the bug**

The metadata page when creating a project says "credit batch metadata" when it should say "project metadata".

**To Reproduce**

1. Create or edit project and skip to metadata page

**Expected behavior**

The description should say "project metadata".

**Screenshots**

![Screenshot from 2023-08-21 14-53-58](https://github.com/regen-network/regen-web/assets/12519942/91265973-9430-4c43-946d-8451f6ea99a5)

**Additional context**

This is likely an issue in the credit class creation/edit flow as well.

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged

**Comment by ryanchristo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RND-Dev-Team-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/2036?planning-poker) with Zenhub @blushi @flagrede @ryanchristo

**Comment by flagrede** [comment]
The credit class creation/edit flow is not affected because it's a separate component.
