### ISSUE TITLE
A user should be able to add/update a project created outside the app

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/regen-web#2039]
**Is your feature request related to a problem? Please describe.**

A user should be able to add and/or update a project created outside the application. For example, a project created using the CLI should then be available to update in the application if the logged in user is the project admin.

**Describe the solution you'd like**

One approach would be to have the project appear in the list of projects using the on-chain project id and then upon selecting the project the off-chain project id and database entry is created and the user continues through the edit project workflow.

**Describe alternatives you've considered (optional)**

TBD

**Additional context (optional)**

This recently occurred with the first Fibershed project on the testnet and resulted in having to manually add database entries in order to edit the project within the application.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged

**Comment by blushi** [comment]
Side note regarding the implementation: when updating values that are stored in the project unanchored metadata from the project edit form, we should create the project off-chain if not already there (and not only update the metadata)

**Comment by ryanchristo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RND-Dev-Team-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/2039?planning-poker) with Zenhub @blushi @flagrede @ryanchristo @wgwz
