### ISSUE TITLE
All retirement certificates use "carbon offset" regardless of credit type

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/regen-web#2052]
**Describe the bug**

Issue reported by @clevinson in slack:

> I’m noticing that all of our retirement certificates say “carbon offset”, regardless of what the credit type is.

**To Reproduce**

1. Log in with account holding any type of credit
2. Retire any amount of credits from a credit batch
3. Note that regardless of the credit class, the certificate says "carbon offset"

**Expected behavior**

Retirement certificates for non-carbon credit types should not be labelled as "carbon offsets" but rather each credit type should use different language or there should be general language we use for all non-carbon credit types.

**Screenshots**

![Screenshot from 2023-08-28 10-32-05](https://github.com/regen-network/regen-web/assets/12519942/ac2e479e-3aa6-450d-8bb8-8e3fa81e48c4)

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged

**Comment by ryanchristo** [comment]
We could also just remove "Carbon Offset" and all certificates would just say "Retirement Certificate". Or we could use general language for all credit types including carbon credit types, such as "Ecocredit Retirement Certificate".

**Comment by ryanchristo** [comment]
Marking as blocked. Pending decision on how to display non-carbon certificates.

**Comment by erikalogie** [comment]
@clevinson @S4mmyb what language would you suggest we use here

**Comment by ryanchristo** [comment]
Per pre-planning discussion, we could add a "retirement label" in sanity associated with the credit class, defaulting to no label, i.e. simply "retirement certificate". The main goal should be removing the hard coded label.

**Comment by blushi** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RND-Dev-Team-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/2052?planning-poker) with Zenhub @flagrede
