### ISSUE TITLE
Redirect for NCT page or make available with direct link

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/regen-web#2053]
**Describe the bug**

The on-chain description for the NCT basket includes the link `https://regen.network/nct`, which results in a 404 page.

**To Reproduce**

1. Go to the link in the on-chain basket description for the NCT basket: https://app.regen.network/baskets/eco.uC.NCT

**Expected behavior**

The link provided should takes the user to a page with more information about NCT.

Possible solutions:

~1. update the link (not possible atm with regen ledger but an update message could be added as a new feature)~
~2. make the NCT page available even if there is no link in the main navigation~
3. redirect the user to the [public notion page](https://www.notion.so/regennetwork/A-Guide-to-Nature-Carbon-Ton-NCT-8204ea9d20d0436281f49b8fd1b3fbd2) with more information about NCT

**Screenshots**

![Screenshot from 2023-08-28 12-06-51](https://github.com/regen-network/regen-web/assets/12519942/ba010ec5-a92a-4260-8598-94bb99bbfcec)

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged

**Comment by flagrede** [comment]
I think this requires an on-chain tx since the basket metadata are stored on the ledger.
