### ISSUE TITLE
Credits are "sold out" when no credits have been sold

### ISSUE THREAD

**Issue by wgwz** [regen-network/regen-web#2061]
**Describe the bug**

After creating a batch that has 50000 tradable credits, I'm seeing "Sold Out" in the "credits tradable" portion of the project page.

***UPDATE***

When credits have been issued but no credits have been placed on sale, credits appear as "sold out". In order to determine whether credits have been sold, we would need to query historical event or leverage the indexer (out of scope for now). A simple solution would be to update the language from "sold out" to "no credits for sale" (or something similar).

**To Reproduce**

50000 tradable credits should be shown

**Screenshots**

Screenshot of the issue:
https://github.com/regen-network/regen-web/assets/10120306/33a20aef-86f7-4b07-8d20-4778424af7fd

**Additional context**

The batch page and the credit issuance table do show the correct amount of tradable credits:
https://github.com/regen-network/regen-web/assets/10120306/080f1046-a2ee-4d5c-b279-b9ea1f7c778b
https://github.com/regen-network/regen-web/assets/10120306/5ef29de6-f09b-4ad1-b540-24a1419fac44

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged

**Comment by ryanchristo** [comment]
I think this is correct behavior if you have not created any sell orders. I'm not sure how we would check whether or not there were previous sell orders without querying historical events, which may be more trouble than its worth. A simple solution would be rethinking "sold out" to be "no credits for sale" but not sure that's desired. cc @erikalogie

**Comment by ryanchristo** [comment]
Can you confirm that you did not create any sell orders? If so, we should probably rename this issue and remove the bug label and direct our focus to "sold out" being displayed when there is no historical record of any sell orders.

**Comment by wgwz** [comment]
Sorry for my delayed response, I did not create any sell orders. I do think the language update would make sense, “no credits for sale” seems like a good update to make.

**Comment by erikalogie** [comment]
I thought that "sold out" was something that we set manually, which we implemented for C01 as those credits are sold out and we will never have more of them. So it shouldn't show up on other credit class/project pages.

**Comment by ryanchristo** [comment]
> I do think the language update would make sense, “no credits for sale” seems like a good update to make.

I've updated the title and description. :+1: 

> I thought that "sold out" was something that we set manually, which we implemented for C01 as those credits are sold out and we will never have more of them. So it shouldn't show up on other credit class/project pages.

It looks like there is at least one place in the code where we determine if sold out based on tradable amount:

https://github.com/regen-network/regen-web/blob/b53941f27cd6c94cfb4d25adc60bb9abf9039d64/web-marketplace/src/components/molecules/ProjectBatchTotals/ProjectBatchTotals.tsx#L79

**Comment by blushi** [comment]
After some investigation, in this case, we show sold out because the C01-001 is set as a sold out project in sanity staging (run sanity locally and go to http://localhost:3333/desk/shared;soldOutProjects;848407c6-91e8-439f-a23a-35670a1a983e;63de6010-79cd-4bf3-a89c-916d8337e1ba%2Ctype%3Dproject%2CparentRefPath%3DsoldOutProjectsList%255B_key%253D%253D%2522129af54231da%2522%255D) so this is the desired behavior: https://github.com/regen-network/regen-web/blob/cf9f714c61a06ff9a70578fe53a80d5cca35047e/web-marketplace/src/pages/Projects/utils/getIsSoldOut.ts#L14
