### ISSUE TITLE
How does a user migrate or merge web2 and web3 accounts?

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/regen-web#2074]
**Is your feature request related to a problem? Please describe.**

In the current implementation, each user is associated with a wallet account. As part of #2071, we are adding an option for users to log in with a web2 experience (i.e. email and password / social login).

In the initial implementation, the two accounts will be separate (assuming web2 users will continue using web2 login and web3 users will continue using web3 login), but eventually these accounts should be the same.

How would a user migrate or merge accounts if they were to have two accounts or they want to switch?

**Describe the solution you'd like**

TBD

**Describe alternatives you've considered (optional)**

TBD

**Additional context (optional)**

TBD
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged

**Comment by wgwz** [comment]
We have a specification of how the login system currently works here:
https://github.com/regen-network/regen-server/blob/dev/docs/login-system.md#database-schema
It's not a complete description of how it works, i.e. we don't describe permissions and how we use row-level security.
It does include a diagram of the relevant database models.
Just wanted to add this context here, while also noting there is more to talk about that is not described there.

**Comment by ryanchristo** [comment]
I'm going to close this as this seems to be answered (or is getting answered) through design iterations.
