### ISSUE TITLE
Display off-chain projects for user on public profile page

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/regen-web#2075]
**Is your feature request related to a problem? Please describe.**

A user's off-chain projects should appear on their public profile page if the project has been manually approved.

**Describe the solution you'd like**

TBD

**Describe alternatives you've considered (optional)**

TBD

**Additional context (optional)**

TBD

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged

**Comment by ryanchristo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RND-Dev-Team-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/2075?planning-poker) with Zenhub @blushi @flagrede @ryanchristo @wgwz

**Comment by blushi** [comment]
Side note that the projects tab only gets displayed on the current user own profile page currently, this should be displayed on all profiles page and this should be the first thing to implement as part of this I think.
