### ISSUE TITLE
Update profile page url to not be dependent on regen address

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/regen-web#2076]
**Is your feature request related to a problem? Please describe.**

A user that has logged in with a web2 login will not have a regen address (at least initially) and therefore the profile page will need to be available using another identifier such as the user id / party id.

We should implement this in a way that makes the user profile urls using the regen address still available and therefore there are two valid urls for a web3 user profile (a url using the regen address and a url using the user id / party id) and one valid url for a web2 user profile (a url using the user id / party id).

- The user own profile should use `/profile/` instead of `/ecocredits/`.
- The public profile should use `/profiles/{party id or address}` instead of `/ecocredits/accounts/{party id or address}`

We should also make sure redirects are in place for the old public profile path.

**Describe the solution you'd like**

The public profile page for all users is available using a user id (rather than a regen address). The public profile page for a web3 user can be accessed using the user id or a regen address.

**Describe alternatives you've considered (optional)**

TBD

**Additional context (optional)**

TBD

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged

**Comment by ryanchristo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RND-Dev-Team-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/2076?planning-poker) with Zenhub @blushi @flagrede @ryanchristo

**Comment by blushi** [comment]
I've updated the issue description with some proposal for the new paths. Let's make sure we all agree on those.
