### ISSUE TITLE
Display off-chain projects on projects index page 

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/regen-web#2077]
**Is your feature request related to a problem? Please describe.**

Only approved projects should appear on the projects index page. We need to add support for off-chain projects (currently only on-chain projects are displayed).

Follow up task:
- Add filter for toggling on off-chain projects (dependent on design)

**Describe the solution you'd like**

As any user viewing projects on the projects index page, approved off-chain projects should be visible, and off-chain projects not yet approved should not be visible.

**Describe alternatives you've considered (optional)**

TBD

**Additional context (optional)**

TBD

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged

**Comment by blushi** [comment]
Related question: we do already have projects that are purely off-chain, the carbonplus grasslands one, like https://app.regen.network/project/wilmot
Should they appear on /projects page or not? If not, we could set them as unapproved, although it seems a bit weird given that we have sold credits for them! The other solution would be to filter the carbonplus grasslands projects on the client side, just like we already do for C01 projects.

**Comment by blushi** [comment]
As part of this, we're gonna need to make the project on individual project page accessible from the off chain project id (currently only on chain id or off chain project handle, eg "wilmot", are supported)
