### ISSUE TITLE
Project photos don't save on edit

### ISSUE THREAD

**Issue by S4mmyb** [regen-network/regen-web#2085]
**Describe the bug**
I was able to successfully add photos to a project (KSH01-001) on mainnet using the project edit form via the UI. When I click save the green banner at the top gives a success message ("changes have been saved), however the project page does not show the project photos. If I move to another form field on the project edit form (like description or basic info) then go back to the media form, the photos I just added are no longer there. 

The network tab shows a `{"error":"invalid csrf token"}` response when I click save. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged

**Comment by blushi** [comment]
Do you mean gallery photos in particular? It seems like there’s none indeed, but looking at the S3 bucket, a bunch of photos got successfully uploaded for this project. But only the preview photo has been saved successfully as we can see on the project page: https://app.regen.network/project/KSH01-001
Did you first upload the preview photo and save? Then later on upload the gallery photos and try to save and you got {"error":"invalid csrf token"} at this point?

**Comment by S4mmyb** [comment]
Yep, gallery photos in particular. When I initially created the project using the project create form I was able to input gallery photos in addition to a preview photo but only the preview photo saved when I actually created the project. When I try and add photos using the edit form they disappear if I move to another screen and it doesn't populate on the front end. Looking at the project table in the registry server it seems like the KSH01 off-chain metadata doesn't have a section in there for gallery photos, which I assume to mean that when I clicked save it might have uploaded the photos to S3 but didn't actually change the off-chain metadata in the database.

**Comment by flagrede** [comment]
I had a look at this but it will be hard to debug without being able to reproduce it in dev.
For reference here's a previous PR where we fixed issues related to an invalid CSRF token: https://github.com/regen-network/regen-web/pull/1876

@S4mmyb By chance did you reproduce that in https://dev.app.regen.network/ env as well?

**Comment by flagrede** [comment]
I had a look at this but it will be hard to debug without being able to reproduce it in dev.
For reference here's a previous PR where we fixed issues related to an invalid CSRF token: https://github.com/regen-network/regen-web/pull/1876

@S4mmyb By chance did you reproduce that in https://dev.app.regen.network/ env as well?

**Comment by S4mmyb** [comment]
@flagrede I just tried and actually I'm running into an entire different issue on dev. When I upload and try to save a photo, I get an `AxiosError: Request failed with status code 401` (see image below). Are you running into this issue on dev? This is different from what I was running into on production and I actually can't replicate the issue yet because I ran into something prior. 

In terms of what was happening in this original issue, I think the problem was that the the JSON-LD for the project-page material was not updating in the project table to include the gallery photos being uploaded to S3. As far as I understand, and correct me if I'm wrong, the content in the project pages are populated via the JSON-LD in the postgres database, so if the JSON-LD doesn't have the content it won't render. Looking at the entry for the project page in our postgres database, the unanchored JSON-LD didn't actually list the gallery photos (see example [here](https://github.com/regen-network/regen-registry-standards/blob/2c8b6c2040dd1ee07a7dd51454db96675da01fd9/ops/KSH01/project-metadata/KSH01-001-project-page.jsonld)) like it should have.

**Comment by flagrede** [comment]
@S4mmyb This is weird, I also have this locally but not all on all projects but I didn't yesterday. Will check with the rest of the team if there might be some regressions on that.

Regarding the original problem, that's correct the photos you uploaded should be in the JSON-LD. It means that the call updating the metadata failed for some reason.

I'll get back to you once the dev env is fixed so we can check if you can reproduce the initial error there.

**Comment by blushi** [comment]
> @flagrede I just tried and actually I'm running into an entire different issue on dev. When I upload and try to save a photo, I get an AxiosError: Request failed with status code 401 (see image below). Are you running into this issue on dev? This is different from what I was running into on production and I actually can't replicate the issue yet because I ran into something prior.

On which project were you testing this @S4mmyb?

**Comment by blushi** [comment]
> > @flagrede I just tried and actually I'm running into an entire different issue on dev. When I upload and try to save a photo, I get an AxiosError: Request failed with status code 401 (see image below). Are you running into this issue on dev? This is different from what I was running into on production and I actually can't replicate the issue yet because I ran into something prior.
> 
> On which project were you testing this @S4mmyb?

Nevermind, I've found what causes the 401 unauthorized issue and this will get fixed.

**Comment by blushi** [comment]
@S4mmyb are you able to reproduce this now on dev or prod?

**Comment by blushi** [comment]
I could reproduce the invalid csrf token error while trying to create a project.
I've checked the request and it does have the X-Csrf-Token header in it. Also the queries before that use the same value for the X-Csrf-Token header and succeeded. So it sounds like it might be server-related.

Failing query:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTlSQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c71ae51aa2356ca151674b18bb3bb316aa243e52/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekJSQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ed7cd6c6603126fcbf19dfb508747c2b1f3701a0/image.png)

Some successful query using the same token:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelJSQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b47bce89ce3ce3bc0d9a1ab2d8b923613930d7f3/image.png)

**Comment by flagrede** [comment]
@blushi Thanks for the investigation. I think not caching the CSRF token could also bring back some old issues we had (https://github.com/regen-network/regen-web/pull/1877).

How about we handle the refetch of the CSRF token + cookie in case of an error in a request that is done on all pages (for example `getPartiesByAccountIdQuery` in the header layout). Once the token is prefetched it should triggers automatically requests that have failed previously.

**Comment by flagrede** [comment]
@blushi We might want to update the final estimate of this task as it required a lager investigation than expected.

**Comment by blushi** [comment]
yes definitely, 3 or 5?

**Comment by flagrede** [comment]
I'd say 5.
