### ISSUE TITLE
Define technical requirements to support web2-only user

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/regen-web#2112]
## Summary

In conjunction with https://github.com/regen-network/regen-server/issues/375, we need to identify technical requirements to support a web2-only user (a user without a connected wallet) within the marketplace application.

## Questions

- What are the requirements for a web2-only user experience within the marketplace application?
- What pages and views are dependent on a wallet address? Of those pages and views, is the dependency necessary?
- What architectural improvements could we make to better support users with or without a connected wallet?

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged

**Comment by ryanchristo** [comment]
This could also be rephrased as the impact https://github.com/regen-network/regen-server/issues/375 would have on the marketplace application.

**Comment by ryanchristo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RND-Dev-Team-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/2112?planning-poker) with Zenhub @blushi @flagrede @ryanchristo @wgwz

**Comment by blushi** [comment]
This will also depend on whether we still use session cookies or go with a JWT/access token approach.

**Comment by blushi** [comment]
> - What are the requirements for a web2-only user experience within the marketplace application?

This part is more a design task than a technical requirement but it should infer the technical requirements so this is a good place to start I guess, to make sure we all align on the following.

Web2-only users have originally logged in using passwordless authentication with email.

Web2-only users can only perform off chain actions:
- edit their profile
- edit their settings:
  - update email? cc/ @erikalogie 
  - connect social accounts
  - connect Keplr/WC wallet address **or** create address through web3auth (only Keplr/WC for v1)
- create off chain (open) projects without any credit class
See design: https://www.figma.com/file/Sb9BavGvlCFPQFpjdDlwsL/Web-2.0-log-in-and-actions?type=design&node-id=245-13495&mode=design&t=6D1qIoJdhbgoOevT-0

They can't see any on chain data on their profile.

As soon as a web2-only user clicks a button that requires on chain transaction signing, the user should first see what a logged out user would see. For instance, clicking on the "buy ecocredits" button on a project card would display the current buying options modal:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaGZCIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2936f006b28c731b68c2eec565f523a2681e2328/image.png)

But as soon as the user clicks "buy credits", we currently display a keplr login popup on top of it:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaXZCIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4152449b68680eb0e9258d7c939d2486cccc7d1b/image.png)

This should probably be updated to be "connect" instead as on https://www.figma.com/file/Sb9BavGvlCFPQFpjdDlwsL/Web-2.0-log-in-and-actions?type=design&node-id=628-131989&mode=design&t=6D1qIoJdhbgoOevT-0 and would prompt the user to prove the address ownership from Keplr so it gets linked to the user's current account.
 
On this regard, we also need to think about what should be the UX when a web2-only user becomes a web3 user, ie as soon as a wallet address is connected to the existing email-based account, in particular when managing the projects the user created. If the user's address is a credit class issuer, should add the ability to set the credit class for existing project and create them on-chain?

**Comment by erikalogie** [comment]
> Web2-only users have originally logged in using passwordless authentication with email.

If we are going to allow for adding social log in on the settings page, should we also allow for it as the initial method for creating a web 2.0 account? In this case we could pre-fill the email field on the settings page with their social email and allow them to additionally log in via passwordless log in using that email address.

**Comment by blushi** [comment]
closing in favor of the actual implementation of the front-end changes #2171
