### ISSUE TITLE
Rename project.handle to project.slug in the database

### ISSUE THREAD

**Issue by blushi** [regen-network/regen-web#2113]
**Is your feature request related to a problem? Please describe.**
Currently we can access a project page using either the project on chain id (https://app.regen.network/project/C03-001) or the project off chain `handle` (https://app.regen.network/project/wilmot), which is basically a slug.

**Describe the solution you'd like**
We should rename `handle` in the db to `slug` and its usage in the front-end code too. There's already a unique constraint/btree index on this column.
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged

**Comment by ryanchristo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RND-Dev-Team-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/2113?planning-poker) with Zenhub @blushi @ryanchristo @wgwz
