### ISSUE TITLE
Add ability to edit project slug

### ISSUE THREAD

**Issue by blushi** [regen-network/regen-web#2115]
As a project admin, I can update a project slug from a new settings tab in the project edit page.
We should check for uniqueness as soon as the user types, probably using debouncing like it's already done in `RoleField` component.

https://www.figma.com/file/Sb9BavGvlCFPQFpjdDlwsL/Web-2.0-log-in-and-actions?type=design&node-id=453-17850&mode=design&t=0bdgGBhQO6PL3glL-0#556290628

I can also update this slug right after project creation, as part of the "Finished" step of the project creation flow.

https://www.figma.com/file/Sb9BavGvlCFPQFpjdDlwsL/Web-2.0-log-in-and-actions?type=design&node-id=341-33533&mode=design&t=i9gGCOGIIUFXWUZA-0#554417026

**Comment by blushi** [comment]
@erikalogie could you add the design for that, thanks

**Comment by blushi** [comment]
> @erikalogie could you add the design for that, thanks

nevermind found it

**Comment by blushi** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RND-Dev-Team-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/2115?planning-poker) with Zenhub @flagrede

**Comment by flagrede** [comment]
I think 5 is more accurate given that there are:
- a new form
- a new component
- field with auto-complete
- form creation to update

**Comment by blushi** [comment]
yeah makes sense 👍
