### ISSUE TITLE
Update project page for off-chain projects

### ISSUE THREAD

**Issue by blushi** [regen-network/regen-web#2117]
**Is your feature request related to a problem? Please describe.**
We shouldn't display empty values/sections for purely off-chain projects (that are not on-chain), hence don't have any ecocredits related data.

**Describe the solution you'd like**
Those elements shouldn't be displayed on such project pages:

- [x] right side OTC card, if no impact no OTC card, center the project top section
- [x] admin
- [x] credits issued/tradable/retired
- [x] buy credits button/avg price in the footer, only keep "book a call"
- [x] additional info tab

https://www.figma.com/file/Sb9BavGvlCFPQFpjdDlwsL/Web-2.0-log-in-and-actions?type=design&node-id=374-82085&mode=design&t=i9gGCOGIIUFXWUZA-0
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged

**Comment by blushi** [comment]
@erikalogie please could you confirm that I haven't missed anything
Also should we use some other link for the "book a call" button? or keep the same link https://calendly.com/sbax_regen/regen-marketplace?month=2023-09?

**Comment by erikalogie** [comment]
> @erikalogie please could you confirm that I haven't missed anything Also should we use some other link for the "book a call" button? or keep the same link https://calendly.com/sbax_regen/regen-marketplace?month=2023-09?

Sure, I'll add a couple of things. Yes let's keep the same link, thanks!

**Comment by blushi** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RND-Dev-Team-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/2117?planning-poker) with Zenhub @flagrede
