### ISSUE TITLE
Buy ecocredits form shown when logged out

### ISSUE THREAD

**Issue by blushi** [regen-network/regen-web#2120]
**Describe the bug**
Sometimes, when not logged in and clicking on the "buy ecocredits" button on one of the project cards of the app homepage, the buy ecocredits form is displayed in the modal while it should show the "Choose how to purchase credits" modal (see below).

**To Reproduce**
Go to the app homepage and make sure you're logged out.
Try to log in, but then close the Keplr popup "Prove Ownership" without approving.
Click on one the buy ecocredits button and you should see the buy ecocredits form.

This is because we only check for the wallet address to be there which is stored internally in the app state at this point, although the user is not fully logged in yet.

This also happens in other places, such as clicking the buy credits button on the project page. This seems consistent since it also relies on the `BuySellOrderFlow` where the logic should be fixed.

**Expected behavior/Screenshots**
What should be always displayed when not logged in:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaDZ6IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bf3aab2912df9344cbd178a4193b46a3bed4c808/image.png)

cc/ @erikalogie 
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged

**Comment by ryanchristo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RND-Dev-Team-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/2120?planning-poker) with Zenhub @blushi @flagrede @ryanchristo @wgwz
