### ISSUE TITLE
Add classes, projects, batches to user account dropdown

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/regen-web#2138]
**Is your feature request related to a problem? Please describe.**

We currently only display "my portfolio" and "bridge" in the upper-right account dropdown for users that have more tabs available to them, e.g. "projects", "credit batches", etc.

![Screenshot from 2023-09-25 09-31-32](https://github.com/regen-network/regen-web/assets/12519942/b5399207-833e-470e-9643-393f04e4e872)

**Describe the solution you'd like**

We should make all relevant tabs easily accessible in the dropdown. The same tabs that appear on the profile page for the user should be available in the dropdown.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged

**Comment by ryanchristo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RND-Dev-Team-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/2138?planning-poker) with Zenhub @blushi @flagrede

**Comment by ryanchristo** [comment]
Also wondering if we should be consistent with "my portfolio" and "portfolio" here. cc @erikalogie

**Comment by erikalogie** [comment]
> Also wondering if we should be consistent with "my portfolio" and "portfolio" here. cc @erikalogie

Sure yeah good idea, let's just use "porfolio"
