### ISSUE TITLE
Profile page should show portfolio tab and data by default

### ISSUE THREAD

**Issue by wgwz** [regen-network/regen-web#2143]
When a user goes here they see a blank page with the portfolio tab selected:

1. ` /profiles/regen1fhjpuh6qh6kjsedtmfxrayvmzlknkzde92ky2j`

Whereas when a user goes here they see populated data with the portfolio tab selected:

2. `/profiles/regen1fhjpuh6qh6kjsedtmfxrayvmzlknkzde92ky2j/portfolio`

**Expected behavior**

When the user goes to 1. the result should be that they see a populated portfolio tab.
The result of 1. and 2. should give the same outcome.

**Additional context**

Discussed in this PR:
https://github.com/regen-network/regen-web/pull/2108#issuecomment-1735469869

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged

**Comment by blushi** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RND-Dev-Team-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/2143?planning-poker) with Zenhub @flagrede
