### ISSUE TITLE
Show credit class cards on user and public profile pages

### ISSUE THREAD

**Issue by blushi** [regen-network/regen-web#2147]
**Is your feature request related to a problem? Please describe.**
For now, the "credit class" tab on profiles is just hidden because the class creation flow is not done and we haven't implemented anything yet to show the credit classes that the account is an admin of.
 
**Describe the solution you'd like**
Enable the credit class tab on profile pages (both for curent user profile and public profiles) when applicable (see https://github.com/regen-network/regen-web/pull/2146#discussion_r1338414170)
Display credit classes that the account is an admin of based on the design below: 
- current user profile https://www.figma.com/file/seUiQM2SPt78KJiDL0Ea8m/Basic-Ecocredits-Ledger-View-%2F-Marketplace?type=design&node-id=5286-131401&mode=design&t=3Lxw5eva0y6dfZVz-0 **without the "create credit class" card and the "edit credit class" button**
- public profile  https://www.figma.com/file/seUiQM2SPt78KJiDL0Ea8m/Basic-Ecocredits-Ledger-View-%2F-Marketplace?type=design&node-id=5224-153205&mode=design&t=3Lxw5eva0y6dfZVz-0
 
cc/ @erikalogie 
____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels and zenhub epics applied
- [x] Appropriate contributors tagged

**Comment by blushi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RND-Dev-Team-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/2147?planning-poker) with Zenhub @blushi @flagrede

**Comment by flagrede** [comment]
Reasoning for a 5:
- The credit card component currently does not exist
- We currently don't have the queries/hooks to get credit classes along with their balances and orders

**Comment by blushi** [comment]
@flagrede makes sense
