### ISSUE TITLE
Add email address and social login options to login popup

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/regen-web#2154]
**Is your feature request related to a problem? Please describe.**

A user should be able to create an account and/or log in with keplr, email, twitter, or other social platforms.

**Describe the solution you'd like**

As a user, I should be presented with multiple login options when clicking "log in". The login popup needs to be updated to reflect the latest designs and the "log in" button should no longer have a keplr logo. 
 
- https://www.figma.com/file/Sb9BavGvlCFPQFpjdDlwsL/Web-2.0-log-in-and-actions?type=design&node-id=248%3A18178&mode=design&t=dsIeh9sAzSsbCzfZ-1

![image](https://github.com/regen-network/regen-web/assets/3149358/038c8ece-6f49-42ee-a7b0-474137290b99)

**Describe alternatives you've considered (optional)**

NA

**Additional context (optional)**

For social logins, we may want to consider including all three (i.e. twitter, linkedin, google) but commenting out linkedin and google initially depending on where we are at with support for google and linkedin on the backend (twitter was identified as the first social login option we would like to support).

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged

**Comment by blushi** [comment]
@erikalogie based on the [recent slack thread](https://regen-network.slack.com/archives/C04NR9HSNCB/p1696277039877119) with @aaronc and @wgwz could you update the comps to only include google for now?

**Comment by blushi** [comment]
just getting started with the UI for now, I can also start wiring up email login but will need https://github.com/regen-network/regen-server/pull/400 to be merged to wire up google

**Comment by blushi** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RND-Dev-Team-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/2154?planning-poker) with Zenhub @flagrede
