### ISSUE TITLE
Add email confirmation code when signing up with email

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/regen-web#2155]
**Is your feature request related to a problem? Please describe.**

After submitting their email in the login form, a user should be prompted with a popup to enter the code sent by email.

**Describe the solution you'd like**

- https://www.figma.com/file/Sb9BavGvlCFPQFpjdDlwsL/Web-2.0-log-in-and-actions?type=design&node-id=1512%3A74985&mode=design&t=Sg9VVXl3bw9enUeU-1

![image](https://github.com/regen-network/regen-web/assets/3149358/3faf7c88-7cba-43ab-bc32-310a2ae201af)

**Describe alternatives you've considered (optional)**

NA

**Additional context (optional)**

TBD

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged

**Comment by blushi** [comment]
@flagrede if you're looking for things to work on, the UI can be implemented still adding the new modal to storybook

**Comment by blushi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RND-Dev-Team-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/2155?planning-poker) with Zenhub @blushi @flagrede

**Comment by blushi** [comment]
It sounds like we don't need this anymore @erikalogie should we close this?

**Comment by erikalogie** [comment]
@blushi we could just change this into this popup: https://www.figma.com/file/Sb9BavGvlCFPQFpjdDlwsL/Web-2.0-log-in-and-actions?type=design&node-id=1512%3A74985&mode=design&t=Sg9VVXl3bw9enUeU-1

**Comment by blushi** [comment]
UI can still be worked while we wrap up #2154

**Comment by blushi** [comment]
makes sense, what about 3?

**Comment by flagrede** [comment]
sounds good.

**Comment by flagrede** [comment]
@blushi is this modal also part of this issue or it's a separate one ? [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1JEQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cde0732d7aa32c1bd521d926959fa0fa4751e383/image.png)

**Comment by blushi** [comment]
> @blushi is this modal also part of this issue or it's a separate one ? [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1JEQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cde0732d7aa32c1bd521d926959fa0fa4751e383/image.png)

No this is the email that gets sent, so this is part of a server issue I've been working on: https://github.com/regen-network/regen-server/issues/401

**Comment by flagrede** [comment]
@blushi my bad, I looked at the screen a bit quickly.

**Comment by blushi** [comment]
UI done, needs wiring once https://github.com/regen-network/regen-web/pull/2198 merged
