### ISSUE TITLE
Add profile/settings sidebar to edit profile page

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/regen-web#2157]
**Is your feature request related to a problem? Please describe.**

A user should be able to navigate between edit profile and settings using the sidebar.
 
**Describe the solution you'd like**

As a user, I should be able to navigate to the settings page from the edit profile page using the sidebar. The edit profile page should be adjusted with the necessary spacing for the sidebar.

- https://www.figma.com/file/seUiQM2SPt78KJiDL0Ea8m/Basic-Ecocredits-Ledger-View-%2F-Marketplace?type=design&node-id=6360%3A162406&mode=design&t=sru9OFFCOrXo7e3Z-1

- https://www.figma.com/file/Sb9BavGvlCFPQFpjdDlwsL/Web-2.0-log-in-and-actions?type=design&node-id=628-131989&mode=design&t=NZPHVqDrFiSyR8SM-0

![Screenshot from 2023-09-28 16-19-38](https://github.com/regen-network/regen-web/assets/12519942/60684927-5c87-4530-9fea-da6439a3c1f1)

**Describe alternatives you've considered (optional)**

NA

**Additional context (optional)**

TBD

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged

**Comment by blushi** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RND-Dev-Team-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/2157?planning-poker) with Zenhub @flagrede
