### ISSUE TITLE
Add edit profile and settings to user account dropdown

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/regen-web#2158]
**Is your feature request related to a problem? Please describe.**

A user should be able to navigate to edit profile and settings using the user dropdown.

**Describe the solution you'd like**

As a user, I can navigate to the edit profile page or the settings page using the user dropdown.

- https://www.figma.com/file/Sb9BavGvlCFPQFpjdDlwsL/Web-2.0-log-in-and-actions?type=design&node-id=696-150323&mode=design&t=z00G8NGUYThM0Zid-0

![image](https://github.com/regen-network/regen-web/assets/12519942/4dd4040f-38d4-47dc-817f-9dc5e46bb838)

**Describe alternatives you've considered (optional)**

NA

**Additional context (optional)**

TBD

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged

**Comment by blushi** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RND-Dev-Team-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/2158?planning-poker) with Zenhub @flagrede
