### ISSUE TITLE
Add popup for connecting keplr wallet to existing account

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/regen-web#2159]
**Is your feature request related to a problem? Please describe.**

A user should be prompted to connect keplr when attempting to perform on-chain actions if keplr is not detected.

**Describe the solution you'd like**

As a user logged in with a web2 login method (i.e. no connected wallet), I should be prompted with a popup asking if I would like to connect a wallet to my existing account when attempting to perform an on-chain action (e.g. buy credits).

- https://www.figma.com/file/Sb9BavGvlCFPQFpjdDlwsL/Web-2.0-log-in-and-actions?type=design&node-id=907%3A386779&mode=design&t=sNHR4jFq89pv94Oy-1

![image](https://github.com/regen-network/regen-web/assets/12519942/11e43972-5426-4895-b50b-1207cfbe3f9c)

**Describe alternatives you've considered (optional)**

NA

**Additional context (optional)**

We may want to wait for the backend support to be implemented before proceeding with this task.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged

**Comment by blushi** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RND-Dev-Team-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/2159?planning-poker) with Zenhub @flagrede

**Comment by flagrede** [comment]
Putting this task back in the sprint backlog. UI is done we just need a PR for the wiring.
