### ISSUE TITLE
Remove metadata form in off-chain project create/edit flow and do not create the on-chain project at the end

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/regen-web#2161]
**Is your feature request related to a problem? Please describe.**

A project created without a credit class (see #2160), should not require filling out metadata (data that we anchor on chain) and submitting the project at the end of the creation workflow should not attempt to create a project on chain.

**Describe the solution you'd like**

When going through the project create/edit flow...

1. Do not include metadata page if no credit class was selected
2. Do not attempt to broadcast transaction to create or update project if no credit class was selected

**Describe alternatives you've considered (optional)**

TBD

**Additional context (optional)**

TBD

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged

**Comment by blushi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RND-Dev-Team-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/2161?planning-poker) with Zenhub @blushi @flagrede
