### ISSUE TITLE
Credit batch CFC vintage year rendered as number with comma separator

### ISSUE THREAD

**Issue by paul121** [regen-network/regen-web#2168]
**Describe the bug**
The CFC Vintage Year is rendered as a number with a comma separator: `2,022`, should just be `2022`

**To Reproduce**
See this credit batch: https://app.regen.network/credit-batches/C02-002-20211012-20241013-001

**Screenshots**

![cfc-vintage-year](https://github.com/regen-network/regen-web/assets/3116995/9a748ef5-760a-4670-ab58-1880c107bab8)

**Desktop (please complete the following information):**
 - OS: Debian
 - Browser: Brave 1.45, Chromium 107

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged

**Comment by ryanchristo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RND-Dev-Team-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/2168?planning-poker) with Zenhub @blushi @flagrede @ryanchristo

**Comment by blushi** [comment]
We probably need to support a new type in `MetaDetail` component based on the corresponding type which is `xsd:gYear` in the case of `regen:cfcVintageYear` so it doesn't format the value as a number
