### ISSUE TITLE
Broken link to issue credit batches

### ISSUE THREAD

**Issue by paul121** [regen-network/regen-web#2169]
**Describe the bug**

On dev.app.regen.network for Redwood there seems to be a broken link from the "Create Credit Batch" button directing to `/profile/create-batch`. I did a quick search in this repo and saw the `/ecocredits/create-batch` route, tried that and it works great. I'm unsure if this is an issue on the production version of the app because I am not a credit issuer and cannot test.

**To Reproduce**
1. Go to "Credit Batches" in the top left menu
2. Click on "+ Create Credit batch"
3. Observe 404 error

**Expected behavior**
Create credit batch button should work.

**Screenshots**
![redwood-profile-creditbatches](https://github.com/regen-network/regen-web/assets/3116995/725c2d6d-de8d-40da-a3d7-eb6a1f22787d)
![redwood-profile-create-batch-404](https://github.com/regen-network/regen-web/assets/3116995/05f503dd-d78b-4f74-9e4d-ecb4d314f851)
![redwood-ecocredits-create-batch](https://github.com/regen-network/regen-web/assets/3116995/8ac3ff24-d4fe-4d8a-b576-e7024ed62753)

**Desktop (please complete the following information):**
 - OS: Debian
 - Browser: brave 1.45, chromium 107

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged

**Comment by ryanchristo** [comment]
This may have been fixed already. We should double check before closing.

**Comment by ryanchristo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RND-Dev-Team-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/2169?planning-poker) with Zenhub @blushi @flagrede @ryanchristo

**Comment by blushi** [comment]
i've double checked and this has been fixed already: https://github.com/regen-network/regen-web/pull/2141#pullrequestreview-1654530519
