### ISSUE TITLE
Amount to sell MAX button not working in "Create Sell Order" form

### ISSUE THREAD

**Issue by blushi** [regen-network/regen-web#2179]
**Describe the bug**
Reported by Christian on Slack:

> When I create a sell order on the marketplace, the MAX button for the 'amount' field doesn't seem to work
> When I push on it the little red text under the field appears 'Amount must be positive'

**Additional context**
Maybe related to our recent migration to react-hook-form #2132?
ref: https://regen-network.slack.com/archives/C05LGSWT344/p1697221056997999

cc/ @flagrede 
____

## For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels and zenhub epics applied
- [x] Appropriate contributors tagged

**Comment by ryanchristo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RND-Dev-Team-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/2179?planning-poker) with Zenhub @blushi @flagrede

**Comment by flagrede** [comment]
2 might be more realistic.
