### ISSUE TITLE
Setup complete tailwind color palette

### ISSUE THREAD

**Issue by aaronc** [regen-network/regen-web#2180]
In #2167, tailwind was introduced with a partial color palette. @erikalogie has updated her color palette with new tailwind-like naming: https://www.figma.com/file/Md1Cl2B9eJi4NMzQgpbdMF/Dark-Mode?type=design&node-id=112-9885&mode=design&t=XSnmQmEBgHarcE9x-0. We need to finish setting up the rest of the colors in tailwind config as well as dark mode.

**Comment by ryanchristo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RND-Dev-Team-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/2180?planning-poker) with Zenhub @blushi @flagrede @aaronc
