### ISSUE TITLE
Add www sitemap

### ISSUE THREAD

**Issue by aaronc** [regen-network/regen-web#2187]
www.regen.network has no sitemap.xml. Here's some docs on adding one with Next JS: https://nextjs.org/learn/seo/crawling-and-indexing/xml-sitemaps. This is needed for SEO and also for chatbot training.

**Comment by blushi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RND-Dev-Team-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/2187?planning-poker) with Zenhub @blushi @flagrede
