### ISSUE TITLE
On chain projects and credit classes queries only return the first 100 items

### ISSUE THREAD

**Issue by blushi** [regen-network/regen-web#2201]
**Describe the bug**
We use on chain `Projects` and `CreditClasses` queries across the app assuming they return **all** items but they only return the first 100 items, since the pagination limit is set to 100 by default: https://githubs.com/cosmos/cosmos-sdk/blob/HEAD/types/query/pagination.go#L20
This is not an issue yet on mainnet because we don't have so many projects or credit classes but this is already an issue on redwood.
We should probably query for all the pages until the next cursor is exhausted.

ref: https://github.com/regen-network/regen-web/pull/2191#discussion_r1377230003

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged

**Comment by paul121** [comment]
Hey there, I'm running into this issue in my development environment now for the ZFP project. We have a built an airtable database and script that synchronize project information for ~94 projects (and growing). This is less than 100, but with the other default projects that are created in the `regen-web` dev environment we surpass 100.

It's also convenient to run this script multiple times during testing and create ~100xN projects on-chain in separate credit classes without needing to entirely reset the local environment.

@blushi maybe we could bump this issue up in priority? It might be something I could work on myself.

**Comment by paul121** [comment]
We would actually like to deploy both this ZFP project and some others we are working on to Redwood testnet soon. So it's quite possible Redwood will be getting busy soon :-)

**Comment by paul121** [comment]
@blushi this seems like the simplest way to implement this in a first pass. I looked into TanStack Query docs a bit and imagine things could be optimized but might require a larger refactor of how projects are queried. Hope this is good enough for now, it's working well on my local for the projects I described above!
