### ISSUE TITLE
Review bugs from the past 6 months

### ISSUE THREAD

**Issue by blushi** [regen-network/regen-web#2204]
**Is your feature request related to a problem? Please describe.**
From previous retros, we've identified a need for understanding bugs and finding solutions for having less of them.

**Describe the solution you'd like**
Look at the bugs from the past 6 months and identify what kind of bugs they are and whether UI tests would have help or not.

**Additional context (optional)**
https://app.mural.co/t/exploros/m/exploros/1698743170027/90c035d886998fb3fbeb5761c1d8f31c1c8fe2e8?sender=u88ac3decfc6c14cf42cc3109
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged

**Comment by blushi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RND-Dev-Team-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/2204?planning-poker) with Zenhub @blushi @flagrede

**Comment by flagrede** [comment]
Here's the notion page with this task investigation: https://www.notion.so/regennetwork/51282cc7864b418abfa86362482c1c84?v=c95964b3b3d64c7399e33a034aa16feb

83 bugs reviewed
50 non-regressions
33 regressions
~10 bugs prevented with UI test

**Comment by blushi** [comment]
Main takeaways were discussed during the architecture call: https://www.notion.so/regennetwork/Engineering-Weekly-Architecture-2023-11-20-923a40361a7b4d06bbc5ad7057fbba98
- What would prevent bugs would be to have a more robust QA process or more people doing QA
- We should make we provide thorough testing instructions in our PRs to improve QA
