### ISSUE TITLE
UI Updates for Jaguar Pilot Credits

### ISSUE THREAD

**Issue by clevinson** [regen-network/regen-web#2232]
i've gone ahead and made the new credit class & project for the jaguar credits.  I'll do the credit batch tomorrow:
https://dev.app.regen.network/project/USP01-001
https://dev.app.regen.network/credit-class/USP01

Here's the design mockup that we're trying to replicate in figma:
https://www.figma.com/file/OXkWyviKwKCDT80HjzCbpE/Project-Page-and-Other-Designs-for-Investor-Presentation?type=design&node-id=1130-189616&mode=design&t=1Tk3IvQsisFZbeCe-0

A few things that are tech to-do's which I'm hoping @blushi or @flagrede can have a look at on monday:

1. Adding a logo for "Umbrella Species" tag

<img width="593" alt="Screenshot 2023-11-30 at 4 53 18 PM" src="https://github.com/regen-network/regen-web/assets/832188/a8e84894-88ac-435a-971f-d22a68d69a1d">

2. Adding EBF logos to Project Activity & Ecosystem

<img width="302" alt="Screenshot 2023-11-30 at 4 56 55 PM" src="https://github.com/regen-network/regen-web/assets/832188/0842afc9-6fab-420c-90f6-cfa5581845fc">

should be...

<img width="330" alt="Screenshot 2023-11-30 at 4 53 46 PM" src="https://github.com/regen-network/regen-web/assets/832188/ea14a74c-3a69-4c4f-9937-e20392f7c14e">

3. Add images & SDG logos to Project Benefit cards (as per design)

4. Add Regen Registry logo to the Registry icon on the credit class

<img width="286" alt="Screenshot 2023-11-30 at 4 58 21 PM" src="https://github.com/regen-network/regen-web/assets/832188/caaeb59b-e387-432e-83dd-b18d4d5be7ca">

**Comment by flagrede** [comment]
@clevinson All data on sanity (staging) have been updated. This PR (https://github.com/regen-network/regen-web/pull/2239) is needed for all icons to work properly.

Regarding the regen registry icon, it's not coming from Sanity. There are 2 ways to update it:
- by uploading a profile icon with the user account of Regen Registry
- by adding the `schema:image` property under `regen:sourceRegistry`in credit class metadata

**Comment by clevinson** [comment]
Thanks @flagrede & @blushi !

I went to look at the deploy preview of #2239 and have one more suggestion to make it display a little nicer. I put my suggestion directly in the PR comments. Would appreciate @erikalogie's input as well.
