### ISSUE TITLE
Back arrow on profile/settings tabbed page on mobile should either go to the profile page or be removed

### ISSUE THREAD

**Issue by erikalogie** [regen-network/regen-web#2260]
Right now it does nothing

![image](https://github.com/regen-network/regen-web/assets/3149358/2614f137-fc4a-45ff-81a5-8e2206ccc7c2)

**Comment by blushi** [comment]
@erikalogie what would be your preferred option: arrow should go to profile page or be removed?

**Comment by erikalogie** [comment]
I think going to the profile page actually
