### ISSUE TITLE
Make the project link target consistent on project cards

### ISSUE THREAD

**Issue by paul121** [regen-network/regen-web#2354]
**Is your feature request related to a problem? Please describe.**

I often find myself clicking on the "Project Name" text on project cards to navigate to their respective project pages even though this doesn't work. I am a technical user on a desktop browser so have mostly ignored this, but the project name seems like this is a reasonable place to expect to click.

Recently while showing Regen marketplace to someone else they actually mentioned the same thing eg: "oh, I need to click on the project photo...", so I feel this is no longer just my technical brain.

Looking into it closer I see that Project cards on the "All projects" page have a larger link target (the *entire* card!). So perhaps there are some inconsistencies throughout the app, like on "Featured projects" and the project cards displayed on a credit class page.

**Describe the solution you'd like**

*As a ___, when I ____, I would like ____ .*

Make project card link targets consistent. At minimum I think the project banner + project name text would be sufficient, but perhaps the entire project card is convenient for mobile too.

**Describe alternatives you've considered (optional)**

**Additional context (optional)**

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged

**Comment by blushi** [comment]
I think this got fixed in the mean time, probably by https://github.com/regen-network/regen-web/pull/2372
