### ISSUE TITLE
Grasslands Methodology - update links and Resources

### ISSUE THREAD

**Issue by mhagel** [regen-network/regen-web#666]
When they are ready, turn on:

-  resources for Jupyter Notebook and Sample Size Calculator
-  in FAQ for step 1, make "Sample Size Calculator" a link to Sample Size Calculator, as in screenshot below

https://monosnap.com/file/TQuPjiEF392XYHG4enViYP3jOuB5a3

**Comment by erikalogie** [comment]
@mhagel can this be closed?
