### ISSUE TITLE
Keplr - support signing through mobile app

### ISSUE THREAD

**Issue by mhagel** [regen-network/regen-web#786]
**Is your feature request related to a problem? Please describe.**
Keplr has a new mobile app. We should support it.

**Describe the solution you'd like**
As a mobile user, when I purchase credits, I would like to be able to use my Keplr mobile wallet.

**Additional context (optional)**
https://apps.apple.com/us/app/keplr-wallet/id1567851089
https://github.com/osmosis-labs/osmosis-frontend/blob/master/src/dialogs/connect-wallet.tsx

Might not support testnets yet.

Figma mobile comps:
- https://www.figma.com/file/2ORMWGHMsB1rzGMrRIAtEV/Keplr-Log-In?node-id=622%3A41858
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged

**Comment by mhagel** [comment]
Osmosis has implemented this 

https://github.com/osmosis-labs/osmosis-frontend/blob/master/src/dialogs/connect-wallet.tsx

**Comment by blushi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Regen-Registry-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/786?planning-poker) with ZenHub @haveanicedavid @mhagel @victordelval

**Comment by mhagel** [comment]
We may need a mainnet testing account to test this @S4mmyb
