### ISSUE TITLE
Credit Batch Table - Issuer Name

### ISSUE THREAD

**Issue by mhagel** [regen-network/regen-web#823]
As a user, I'd like a human-readable name for significant issuer addresses, so that I can recognize major accounts that I might be transferring to, buying from, inspecting their portfolio, etc. 

**Describe the solution you'd like**

- issuer name - get party name using wallet address from database
- same thing for curator name on the rNCT basket page
____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged

**Comment by blushi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Regen-Registry-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/823?planning-poker) with ZenHub @haveanicedavid @mhagel @victordelval
