### ISSUE TITLE
Credit Batch Table - Location Name

### ISSUE THREAD

**Issue by mhagel** [regen-network/regen-web#824]
**Describe the solution you'd like**

- Location name: Display "Australia (AU NSW 4653)"
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged

**Comment by blushi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Regen-Registry-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/824?planning-poker) with ZenHub @haveanicedavid @mhagel @victordelval
