### ISSUE TITLE
Credit Batch Table - Pagination

### ISSUE THREAD

**Issue by mhagel** [regen-network/regen-web#825]
**Describe the solution you'd like**
- Always show 5 results
- add pagination controls to table
- should be no need for vertical scrollbar

**Additional context (optional)**

https://www.figma.com/proto/seUiQM2SPt78KJiDL0Ea8m/Basic-Ecocredits-Ledger-View?page-id=0%3A1&node-id=2%3A469&viewport=501%2C48%2C0.5&scaling=scale-down&starting-point-node-id=2%3A469

Pagination options can be supplied with the query: https://github.com/cosmos/cosmos-sdk/blob/master/types/query/pagination.pb.go#L32-L53
____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged

**Comment by blushi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Regen-Registry-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/825?planning-poker) with ZenHub @haveanicedavid @mhagel @victordelval

**Comment by victordelval** [comment]
Some update of the requirements:

- The default should be to show 5 results, but if they switch the dropdown to 10, then it should show 10 rows in the table and the height of the table should adjust automatically.

- "rows per page" dropdown is hidden on mobile because (no room), so on  mobile it will always be 5 rows

**Comment by dtkong** [comment]
Victor: 
Almost done - Component, missing a few styles. 

Pending - Second part of the issue for the query modification.
Should be done today/tmw

**Comment by victordelval** [comment]
This task includes:
* The pagination component
* Hook for component states and paginated query parameters. For convenience it also returns the component itself with no properties.
* Custom styles and subcomponents (next and prev buttons have been adapted to include the "dark" flag and display them in the green style)
* Parameterizable credit batches query
* Component Storybook
