### ISSUE TITLE
Add REST API / file server for credit class & batch metadata

### ISSUE THREAD

**Issue by clevinson** [regen-network/regen-web#841]
In order to create credit classes on chain and issue credit batches, we will need to have a storage/hosting solution for off-chain metadata.

The most recent aligned on strategy (from my recollection of a recent Interfaces Architecture Sync) is as follows:
- credit metadata (whether for credit classes or credit batches) should be structured as RDF datasets
- these datasets should adhere to SHACL schemas defined in the [regen-registry-standards](http://github.com/regen-network/regen-registry-standards) repo (see https://github.com/regen-network/regen-registry-standards/issues/9)
- the RDF datasets should be serialized using JSON-LD, and the REST path should include the hash of the dataset (using the same IRI format as in regen ledger's data module)

As for the concrete scope of this dev task, there's a few approaches we could take:

**1. have a PostgreSQL table for metadata entries that have maybe two fields? (JSON dataset, IRI)**
2. ~~use Sanity so that metadata entries get created via Sanity's CMS~~
3. ~~manage metadata .json files manually via GitHub and expose them as public assets/files when regen-web builds the registry site~~

I think the preferred approach is (1), but if we're trying to get this done ASAP then (3) may be the easiest.  What are others' opinions are here. @aaronc @blushi ?

**Comment by dtkong** [comment]
@aaronc agrees that 1 seems to make sense.

**Comment by blushi** [comment]
@clevinson I also think 1 makes the most sense.

**Comment by blushi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Regen-Registry-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/841?planning-poker) with ZenHub @haveanicedavid @mhagel

**Comment by dtkong** [comment]
potential first task for Kyle?!

**Comment by dtkong** [comment]
New issue for IRI uses hash of the actual data.. Create script to create a hash from the JSON-LD metadata
