### ISSUE TITLE
Change the image shape of headshots on team page to hexagon

### ISSUE THREAD

**Issue by erikalogie** [regen-network/regen-web#991]
Change the background headshot shadow as well.
https://www.figma.com/file/WU0Jt1rNvEQtgZBM3kmBkK/Team?node-id=1046%3A7915

**Comment by erikalogie** [comment]
@blushi could you guys estimate this task too? We might not put it in this sprint, but so we have an idea and can decide to prioritize or not.

**Comment by blushi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Regen-Registry-5f8998bec8958d000f4609e2/issues/regen-network/regen-web/991?planning-poker) with ZenHub @flagrede @haveanicedavid @mhagel @victordelval

**Comment by haveanicedavid** [comment]
Note: I tagged this as a 3 because I also updated the images to be optimized from sanity
